### ISSUE TITLE
Not able to bind container group to service

### ISSUE THREAD

**Issue by leifg** [Osthanes/deployscripts#61]
If I am deploying a container group I have the possibility to bind that group to an existing service.

Running it on my command line i can do that as follows:

`cf ic group create --name my_group -e CCS_BIND_SRV=MyService registry.ng.bluemix.net/my_image`

However the group image uses the `CCS_BIND_APP` parameter to bind the group to an app.

Is there  any reason to keep the `CCS_BIND_APP` parameter for deploying a group? Otherwise I suggest replacing it with the `CCS_BIND_SRV` parameter.

In the meantime: Is there a workaround for binding services to container groups?

**Comment by nfritze** [comment]
You can use the "Optional deploy arguments" to use the CCS_BIND_SRV parameter (and just tested, that seems to be working via pipeline and directly).  Some services use old style service binding and do not work with service keys (i.e. BIND_SRV), so the pipeline uses the old style which works with all services.
